lib/bank_accounting_web/router.ex
defmodule BankAccountingWeb.Router do
  use BankAccountingWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BankAccountingWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/api", BankAccountingWeb do
    pipe_through :api
    get "/accounts", AccountController, :list_accounts
    post "/accounts/make-transfer", AccountController, :make_transfer
    get "/accounts/:id", AccountController, :get_balance
  end
end

lib/bank_accounting_web/templates/page/index.html.eex
<div class="container">
    <h1>Manage Bank Accounts</h1>
    <a id="list-accounts" href="<%= account_path(@conn, :list_accounts) %>" hidden></a>
    <a id="make-transfer" href="<%= account_path(@conn, :make_transfer) %>" hidden></a>
    <a id="get-balance" href="<%= account_path(@conn, :get_balance, "_id") %>" hidden></a>
    <hr/>
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm" v-for="account in accounts">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ account.identificator }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">BRL {{ account.balance }}</h1>
                <button v-on:click="getCurrentBalance(account.id)"
                        type="button" class="btn btn-lg btn-block btn-outline-secondary">
                    Check Current Balance
                </button>
                <button v-on:click="openModal(account)"
                    type="button" class="btn btn-lg btn-block btn-outline-primary">Transfer money</button>
            </div>
        </div>
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Contacts</h4>
            <ul>
                <li>
                    <a href="http://github.com/romulocollopy/">Github</a>
                </li>
                <li>
                    <a href="mailto:romulocollopy@pm.me" title="romulocollopy@pm.me">E-mail</a>
                </li>
                <li>
                    <a href="https://linkedin.com/in/romulocollopy">LinkedIn</a>
                </li>
            </ul>
        </div>
    </div>